export const RECEIVE_HOMEDATA = 'receive_homeData'
export const RECEIVE_CATEGORYDATA = 'receive_categoryData'
export const RECEIVE_IDENTIFY_TABS = 'receive_identify_tabs'
export const RECEIVE_IDENTIFY_MANUAL = 'receive_identify_manual'
export const RECEIVE_SEARCHARR = 'receive_searchArr'